language: python
python: "3.6"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coveralls
  - python setup.py build_ext --inplace
  - python coverage run setup.py test
script:
  pytest
after_success:
  coveralls


