language: python
python: "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py build_ext --inplace
script:
  - pytest -x hydsensread -v -rw --cov=hydsensread
after_success:
  - coveralls



